Implement maximum response length
mt-mods/digistuff pull request #41
Opened 2023-11-23 20:07 UTC by Bituvo

This pull request limits the response length of the NIC (to prevent the "message too complex" error). By default, the maximum length is 5,000 characters. This does not affect JSON data.

2023-11-24 06:09 UTC, BuckarooBanzay approved these changes

2023-11-24 07:35 UTC, OgelGames commented
> to prevent the "message too complex" error

How exactly are you producing this error? I tested it just now and I had no issues receiving a message of 2,199,800 characters with a Luacontroller.

The digiline message length limit only applies to messages sent from a Luacontroller, which has nothing to do with the NIC.

2023-11-25 18:02 UTC, Bituvo commented
> How exactly are you producing this error? I tested it just now and I had no issues receiving a message of 2,199,800 characters with a Luacontroller.
> 
> The digiline message length limit only applies to messages sent from a Luacontroller, which has nothing to do with the NIC.

I was taking the last 324 or so characters of the response and sending it to another Luacontroller (which handles textlines).

2023-11-25 22:53 UTC, S-S-X commented
> I was taking the last 324 or so characters of the response and sending it to another Luacontroller (which handles textlines).

I think, if implemented, it should be chopped up into chunks and resulting chunks streamed instead of simply cutting at some obscure position.

This however could also be done with another digiline component, for example with single luacontroller as long as message is at most twice as much as `luacontroller_memsize`. If it is more than that then it'd need multiple memory chips (which can be luacontrollers or anything where you can store data).

But there's limit to this too, unless you're using digiline filter components, which is max heat until memory chips get burnt. With filters you can create enormous memory banks that can store chunks and do the streaming.

2023-11-25 23:04 UTC, S-S-X requested changes
Seems this can be easily done on luac and isn't really needed at all.

I could approve if it included a way to actually get complete message instead of deleting part of it, currently this degrades NIC as it can handle longer content and luac or digilines are also able to handle a lot more than serialization limits.

2023-11-26 14:02 UTC, closed without merging